CREATE TABLE ADDR_LINK (
ADDR_ID BIGINT NOT NULL,
EMP_ID BIGINT,
PRIMARY KEY (ADDR_ID)
);
CREATE TABLE PERSON_TAB (
EMP_ID BIGINT NOT NULL,
FNAME VARCHAR,
LNAME VARCHAR,
PRIMARY KEY (EMP_ID)
);
CREATE TABLE ADDR (
ADDR_ID BIGINT NOT NULL,
CITY VARCHAR,
HOUSE_NO VARCHAR,
STREET VARCHAR,
PRIMARY KEY (ADDR_ID)
);
CREATE TABLE MAIL (
MAIL_ID BIGINT NOT NULL,
MAIL_ADDR VARCHAR,
ADDR_ID BIGINT,
PRIMARY KEY (MAIL_ID)
);
CREATE TABLE PHONE (
PHONE_ID BIGINT NOT NULL,
PHONE_NUMBER VARCHAR,
ADDR_ID BIGINT,
PRIMARY KEY (PHONE_ID)
);

ALTER TABLE ADDR_LINK ADD CONSTRAINT FK_ADDR_LINK_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES PERSON_TAB (EMP_ID);
ALTER TABLE MAIL ADD CONSTRAINT FK_MAIL_ADDR_ID FOREIGN KEY (ADDR_ID) REFERENCES ADDR (ADDR_ID);
ALTER TABLE PHONE ADD CONSTRAINT FK_PHONE_ADDR_ID FOREIGN KEY (ADDR_ID) REFERENCES ADDR (ADDR_ID);

CREATE TABLE SEQUENCE (
SEQ_NAME VARCHAR(50) NOT NULL,
SEQ_COUNT NUMERIC(38),
PRIMARY KEY (SEQ_NAME)
);
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN';
SELECT * FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN';
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);
